version: "3.8"

services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"  # Jupyter Lab
      - "4040:4040"  # Spark Web UI
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=bdm2026
    working_dir: /home/jovyan/work
